package com.yuly.quasar.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.yuly.quasar.converter.SatelliteModelConverter;
import com.yuly.quasar.model.PositionModel;
import com.yuly.quasar.model.SatelliteDefaultModel;
import com.yuly.quasar.model.SatelliteModel;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "satellites")
public class SatellitesEntity {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;

  @DynamoDBAttribute
  @DynamoDBTypeConverted(converter = SatelliteModelConverter.class)
  private SatelliteModel kenobi;

  @DynamoDBAttribute
  @DynamoDBTypeConverted(converter = SatelliteModelConverter.class)
  private SatelliteModel skywalker;

  @DynamoDBAttribute
  @DynamoDBTypeConverted(converter = SatelliteModelConverter.class)
  private SatelliteModel sato;
}
